import { parse } from "csv-parse/sync";
import { Prisma, PrismaClient } from "@prisma/client";
import { buildBinLabel, normalizeBinPart, normalizeIdentifier } from "@/lib/identifiers";

type ImportResult = { rowCount: number; warningCount: number; warnings: string[] };
type ProductRow = { SKU?: string; Name?: string; UPC?: string; ThumbnailUrl?: string; WarehouseLocation?: string; Active?: string; Category?: string; Tag1?: string; Tag2?: string; Tag3?: string; Tag4?: string; Tag5?: string };
type InventoryRow = { SKU?: string; ProductName?: string; WarehouseName?: string; Loc1?: string; Loc2?: string; Loc3?: string; Loc4?: string; OnHand?: string; ReorderThreshold?: string };
export function parseCsv<T>(content: string) { return parse(content, { columns: true, skip_empty_lines: true, trim: true, bom: true }) as T[]; }
export async function importProductCsv(prisma: PrismaClient, content: string, filename: string): Promise<ImportResult> { const rows = parseCsv<ProductRow>(content); const warnings: string[] = []; for (const [index, row] of rows.entries()) { const rowNumber = index + 2; const sku = normalizeIdentifier(row.SKU, { field: `row ${rowNumber} SKU` }); const upc = normalizeIdentifier(row.UPC, { field: `row ${rowNumber} UPC`, expectedLengths: [12, 14] }); warnings.push(...sku.warnings, ...upc.warnings); if (!sku.value || !upc.value) continue; const warehouse = await prisma.warehouse.upsert({ where: { name: row.WarehouseLocation || process.env.ACTIVE_WAREHOUSE_NAME || "Dallas Warehouse" }, update: {}, create: { name: row.WarehouseLocation || process.env.ACTIVE_WAREHOUSE_NAME || "Dallas Warehouse" } }); const product = await prisma.product.upsert({ where: { sku_warehouseId: { sku: sku.value, warehouseId: warehouse.id } }, update: productData(row), create: { sku: sku.value, warehouseId: warehouse.id, ...productData(row) } }); await prisma.productUpc.upsert({ where: { upc_productId: { upc: upc.value, productId: product.id } }, update: {}, create: { upc: upc.value, productId: product.id } }); } await prisma.importBatch.create({ data: { type: "product", filename, rowCount: rows.length, warningCount: warnings.length, warnings: warnings as Prisma.InputJsonValue } }); return { rowCount: rows.length, warningCount: warnings.length, warnings }; }
export async function importInventoryCsv(prisma: PrismaClient, content: string, filename: string): Promise<ImportResult> { const rows = parseCsv<InventoryRow>(content); const warnings: string[] = []; for (const [index, row] of rows.entries()) { const rowNumber = index + 2; const sku = normalizeIdentifier(row.SKU, { field: `row ${rowNumber} SKU` }); warnings.push(...sku.warnings); if (!sku.value) continue; const warehouse = await prisma.warehouse.upsert({ where: { name: row.WarehouseName || process.env.ACTIVE_WAREHOUSE_NAME || "Dallas Warehouse" }, update: {}, create: { name: row.WarehouseName || process.env.ACTIVE_WAREHOUSE_NAME || "Dallas Warehouse" } }); await prisma.product.upsert({ where: { sku_warehouseId: { sku: sku.value, warehouseId: warehouse.id } }, update: { name: row.ProductName || sku.value, warehouseId: warehouse.id }, create: { sku: sku.value, name: row.ProductName || sku.value, warehouseId: warehouse.id } }); const zone = normalizeBinPart(row.Loc1); const aisle = normalizeBinPart(row.Loc2); const rack = normalizeBinPart(row.Loc3); const level = normalizeBinPart(row.Loc4); if (!zone && !aisle && !rack && !level) continue; await prisma.binLocation.upsert({ where: { warehouseId_zone_aisle_rack_level: { warehouseId: warehouse.id, zone, aisle, rack, level } }, update: { label: buildBinLabel(zone, aisle, rack, level), active: true }, create: { warehouseId: warehouse.id, zone, aisle, rack, level, label: buildBinLabel(zone, aisle, rack, level) } }); } await prisma.importBatch.create({ data: { type: "inventory", filename, rowCount: rows.length, warningCount: warnings.length, warnings: warnings as Prisma.InputJsonValue } }); return { rowCount: rows.length, warningCount: warnings.length, warnings }; }
function productData(row: ProductRow) { return { name: row.Name || row.SKU || "Unnamed product", thumbnailUrl: row.ThumbnailUrl || null, category: row.Category || null, tag1: row.Tag1 || null, tag2: row.Tag2 || null, tag3: row.Tag3 || null, tag4: row.Tag4 || null, tag5: row.Tag5 || null, active: String(row.Active || "TRUE").toUpperCase() !== "FALSE" }; }
